spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
  mail:
    host: smtp.163.com
    username: snail_gclq@163.com
    password: gclq527051056
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.woniu.woniuticket.platform_user.mapper: debug
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: pageNum=currentPage,pageSize=pageSize
