spring:
  redis:
    port: 6666
    host: 148.70.167.3
    database: 1
    timeout: 5000
    password: 123
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://cdb-e4a6q0m8.cd.tencentcdb.com:10006/cinema?serverTimezone=GMT%2B8
    username: root
    password: huangyulong123--
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
  mail:
    host: smtp.163.com
    username: snail_gclq@163.com
    password: gclq527051056
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      #总数据大小
      max-request-size: 100MB
      #单个数据的大小
      max-file-size: 100MB
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.woniu.woniuticket.platform_user.mapper: debug
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: pageNum=currentPage,pageSize=pageSize

